FROM node:24-alpine AS frontend-builder

WORKDIR /workspace
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM nginx:stable-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend-builder /workspace/dist /usr/share/nginx/html

EXPOSE 80
