FROM eclipse-temurin:25-jdk-alpine AS builder

WORKDIR /workspace
COPY backend/ ./
RUN chmod +x ./gradlew
RUN ./gradlew --no-daemon clean bootJar
RUN cp build/libs/*.jar /app.jar

FROM eclipse-temurin:25-jre-alpine

WORKDIR /app
COPY --from=builder /app.jar ./app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
